name: Variables
on:
  push:
    branches:
      - feat/new-testing

jobs:
    job_name_1: 
        env: 
            ANIMAL: cat
            BIRD: parrot
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v5

        - name: Variables
          run: | 
                echo $ANIMAL
                echo $BIRD
      
        - name: Variable check
          run: | 
                echo $ANIMAL
                echo $BIRD
            

        

